export const MY_ADOPTION_REQUEST = " MY_ADOPTION_REQUEST";
export const MY_ADOPTION_SUCCESS = " MY_ADOPTION_SUCCESS";
export const MY_ADOPTION_RESET = "MY_ANIMAL_RESET";
export const MY_ADOPTION_FAIL = "MY_ANIMAL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
