export const ALL_ANIMAL_REQUEST = "ALL_ANIMAL_REQUEST ";
export const ALL_ANIMAL_SUCCESS = "ALL_ANIMAL_SUCCESS";
export const ALL_ANIMAL_FAIL = "ALL_ANIMAL_FAIL";

export const PERSONNEL_ANIMAL_REQUEST = "PERSONNEL_ANIMAL_REQUEST ";
export const PERSONNEL_ANIMAL_SUCCESS = "PERSONNEL_ANIMAL_SUCCESS";
export const PERSONNEL_ANIMAL_FAIL = "PERSONNEL_ANIMAL_FAIL";

export const DELETE_ANIMAL_REQUEST = "DELETE_ANIMAL_REQUEST ";
export const DELETE_ANIMAL_SUCCESS = "DELETE_ANIMAL_SUCCESS";
export const DELETE_ANIMAL_FAIL = "DELETE_ANIMAL_FAIL";
export const DELETE_ANIMAL_RESET = "DELETE_ANIMAL_RESET";

export const NEW_ANIMAL_REQUEST = "NEW_ANIMAL_REQUEST ";
export const NEW_ANIMAL_SUCCESS = "NEW_ANIMAL_SUCCESS";
export const NEW_ANIMAL_FAIL = "NEW_ANIMAL_FAIL";
export const NEW_ANIMAL_RESET = "NEW_ANIMAL_RESET";

export const ANIMAL_DETAILS_REQUEST = "ANIMAL_DETAILS_REQUEST";
export const ANIMAL_DETAILS_SUCCESS = "ANIMAL_DETAILS_SUCCESS";
export const ANIMAL_DETAILS_FAIL = "ANIMAL_DETAILS_FAIL";

export const UPDATE_ANIMAL_REQUEST = "UPDATE_ANIMAL_REQUEST";
export const UPDATE_ANIMAL_SUCCESS = "UPDATE_ANIMAL_SUCCESS";
export const UPDATE_ANIMAL_RESET = "UPDATE_ANIMAL_RESET";
export const UPDATE_ANIMAL_FAIL = "UPDATE_ANIMAL_FAIL";

export const UPDATE_HEALTH_REQUEST = "UPDATE_HEALTH_REQUEST";
export const UPDATE_HEALTH_SUCCESS = "UPDATE_HEALTH_SUCCESS";
export const UPDATE_HEALTH_RESET = "UPDATE_HEALTH_RESET";
export const UPDATE_HEALTH_FAIL = "UPDATE_HEALTH_FAIL";

export const UPDATE_ADOPTION_REQUEST = "UPDATE_ADOPTION_REQUEST";
export const UPDATE_ADOPTION_SUCCESS = "UPDATE_ADOPTION_RESET";
export const UPDATE_ADOPTION_RESET = "UPDATE_ADOPTION_RESET";
export const UPDATE_ADOPTION_FAIL = "UPDATE_ADOPTION_FAIL";

export const TRASH_ADOPTION_REQUEST = "TRASH_ADOPTION_REQUEST";
export const TRASH_ADOPTION_SUCCESS = "TRASH_ADOPTION_SUCCESS";
export const TRASH_ADOPTION_RESET = "TRASH_ADOPTION_RESET";
export const TRASH_ADOPTION_FAIL = "TRASH_ADOPTION_FAIL";

export const NEW_ADOPTION_REQUEST = "NEW_ADOPTION_REQUEST";
export const NEW_ADOPTION_SUCCESS = "NEW_ADOPTION_SUCCESS";
export const NEW_ADOPTION_RESET = "NEW_ADOPTION_RESET";
export const NEW_ADOPTION_FAIL = "NEW_ADOPTION_FAIL";

export const ALL_ADOPTION_REQUEST = "ALL_ADOPTION_REQUEST ";
export const ALL_ADOPTION_SUCCESS = "ALL_ADOPTION_SUCCESS";
export const ALL_ADOPTION_FAIL = "ALL_ADOPTION_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const GET_REVIEWS_REQUEST = "GET_REVIEWS_REQUEST";
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_FAIL = "GET_REVIEWS_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CHART_RESCUED_REQUEST = "CHART_RESCUED_REQUEST";
export const CHART_RESCUED_SUCCESS = "CHART_RESCUED_SUCCESS";
export const CHART_RESCUED_FAIL = "CHART_RESCUED_FAIL";

export const CHART_ADOPTED_REQUEST = "CHART_ADOPTED_REQUEST";
export const CHART_ADOPTED_SUCCESS = "CHART_ADOPTED_SUCCESS";
export const CHART_ADOPTED_FAIL = "CHART_ADOPTED_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
