export const HEALTH_PERSONNEL_REQUEST = "HEALTH_PERSONNEL_REQUEST ";
export const HEALTH_PERSONNEL_SUCCESS = "HEALTH_PERSONNEL_SUCCESS";
export const HEALTH_PERSONNEL_FAIL = "HEALTH_PERSONNEL_FAIL";

export const NEW_HEALTH_REQUEST = "NEW_HEALTH_REQUEST";
export const NEW_HEALTH_SUCCESS = "NEW_HEALTH_SUCCESS";
export const NEW_HEALTH_FAIL = "NEW_HEALTH_FAIL";
export const NEW_HEALTH_RESET = "NEW_HEALTH_RESET";

export const DELETE_HEALTH_REQUEST = "DELETE_HEALTH_REQUEST";
export const DELETE_HEALTH_SUCCESS = "DELETE_HEALTH_SUCCESS";
export const DELETE_HEALTH_RESET = "DELETE_HEALTH_RESET";
export const DELETE_HEALTH_FAIL = "DELETE_HEALTH_FAIL";

export const UPDATE_HEALTH_REQUEST = "UPDATE_HEALTH_REQUEST";
export const UPDATE_HEALTH_SUCCESS = "UPDATE_HEALTH_SUCCESS";
export const UPDATE_HEALTH_RESET = "UPDATE_HEALTH_RESET";
export const UPDATE_HEALTH_FAIL = "UPDATE_HEALTH_FAIL";

export const HEALTH_DETAILS_REQUEST = "HEALTH_DETAILS_REQUEST";
export const HEALTH_DETAILS_SUCCESS = "HEALTH_DETAILS_SUCCESS";
export const HEALTH_DETAILS_FAIL = "HEALTH_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
